

for i in range(5):
    try:
        print(a)
    except Exception as e:
        print(i)

